config/routes.rb
BlogTest::Application.routes.draw do

  resources :posts do
  	resources :comments 
	resources :marks
  end
  resources :users 
  resources :sessions
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :posts
	validates :author, :body, :presence => true
        validates :author, :length => { :in => 2..30 }
	validates :body, :length => { :in => 2..500 }
	validates_associated :posts
end

app/models/mark.rb
class Mark < ActiveRecord::Base
	belongs_to :posts
	validates :value, :post_id, :presence => true
	validates_format_of :value, :with => /\A[0-5]\Z/, :on => :create
	validates_associated :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments
	has_many :marks
	belongs_to :users
	validates :title, :body, :user_id, :presence => true
	validates :title, :length => { :in => 2..50 }
	validates :body, :length => { :in => 2..500 }
	validates_associated :comments, :marks
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  attr_accessible :email, :password, :password_confirmation
  has_secure_password
  validates_presence_of :password, :on => :create
  validates :password, :confirmation => true
  validates :password, :length => { :in => 6..12 }
  validates_presence_of :password_confirmation, :message => 'is required'
  validates_presence_of :email, :message => 'is required'
  validates :email, :uniqueness => true
  validates_associated :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

    def require_user
      logger.debug "ApplicationController::require_user"
      unless current_user
        flash[:notice] = "You must be logged in to access this page"
        redirect_to new_session_path
        return false
      end
    end

  helper_method :current_user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def new
		@post = Post.find(params[:post_id])
		@comment = @post.comments.new
		respond_to do |format|
	      		format.html
	      		format.js
		end
	end
	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create("author" => params[:author], "body" => params[:body])
		respond_to do |format|
			format.js
			format.html { redirect_to post_path(@post), notice: 'Comment was successfully created.' }
		end
	end
	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy
	    	respond_to do |format|
	      		format.html { redirect_to post_path(@post), notice: 'Comment was successfully destroyed.'}
	      		format.js
		end
		
	end
end

app/controllers/marks_controller.rb
class MarksController < ApplicationController
	def new
		@post = Post.find(params[:post_id])
		@mark = @post.marks.new
		respond_to do |format|
	      		format.html 
			format.js
		end
	end
	def create
		@post = Post.find(params[:post_id])
		@mark = @post.marks.create("value" => params[:value], "post_id" => params[:post_id])
		$total = 0;
		$nbMarks = 0;
		@post.marks.each do |mark|
			$total = $total + mark.value
			$nbMarks = $nbMarks + 1
		end
		$note = ($total.to_f/$nbMarks.to_f)
		@post.update_attribute(:note, $note)
		respond_to do |format|
			format.html { redirect_to post_path(@post), notice: 'Mark was successfully added.' }
			format.js
		end
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :require_user, :except => [:index, :show]
  # GET /posts
  def index
	@posts = Post.all
    	respond_to do |format|
      		format.html # index.html.erb
    	end
  end

  # GET /posts/:id
  def show
  	@post = Post.find(params[:id])
    	respond_to do |format|
      		format.html # show.html.erb
    	end
  end


  # GET /posts/:id/edit
  def edit
	@post = Post.find(params[:id])
  end

  # GET posts/new
  def new
	@post = Post.new
	respond_to do |format|
      		format.html
      		format.js
	end
  end

  def create
   	@post = Post.create(params[:post])
	
    respond_to do |format|
      	if @post.save
        	format.html { redirect_to posts_path, notice: 'Post was successfully created.' }
		format.js
      	else
        	format.html { redirect_to new_post_path, notice: 'A problem occured, the post has not been created, try again.' }
		format.js
      	end
    end
  end

  def destroy
	@post = Post.find(params[:id])
	@post.comments.each do |comment|
		comment.destroy
	end
	@post.marks.each do |mark|
		mark.destroy
	end
	@post.destroy
    	respond_to do |format|
      		format.html { redirect_to posts_path, notice: 'Post was successfully deleted.'}
      		format.js
	end
  end
  def update
	@post = Post.find(params[:id])
	@post.marks.each do |mark|
		mark.destroy
	end
	@post.note = 0.0
    	respond_to do |format|
	      	if @post.update_attributes(params[:post])
			format.html { redirect_to posts_path, notice: 'Post was successfully updated.' }
	      	else
			format.html { redirect_to edit_post_path(@post), notice: 'A problem occured, try to edit again.'}
	      	end
    	end
	
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to posts_path, :notice => "Logged in!"
    else
      flash[:error] = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to posts_path, :notice => "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.create(params[:user])
    if @user.save
      session[:user_id]=@user.id
      redirect_to posts_path, :notice => "Signed up!"
    else
      flash[:error] = "Email has already been taken"
      render "new"
    end
  end
  def destroy
	@user = User.find(params[:id])
	@user.destroy
	session[:user_id]=nil
    	respond_to do |format|
      		format.html { redirect_to posts_path, notice: 'Your account was successfully deleted.'}
      		format.js
	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_commentform.html.erb
<%= form_tag("/posts/#{@post.id}/comments", :name => "commentform", :remote=>true) %>

  <div class="field">
    <%= label_tag :author %><br />
	<% if session[:user_id] then %>
		<%= text_field_tag :author, User.find(session[:user_id]).email %>
	<% else %>
    		<%= text_field_tag :author %>
	<% end %>
  </div>
  <br />
  <div class="field">
    <%= label_tag :body %><br />
    <%= text_area_tag :body %>
  </div>
  <div class="actions">
    <%= submit_tag value = "Create Comment" %>
  </div>

app/views/comments/create.js.erb
$("body table tbody").append("<tr><td><%= escape_javascript(@comment.author)%></td><td><%= escape_javascript(@comment.body)%>&nbsp; &nbsp;</td><td><%= escape_javascript(button_to('Delete Comment', "/posts/#{@post.id}/comments/#{@comment.id}", :method => "delete", :style => "background: #F1F1F1; color: #2CA2AF; width:130px; height: 19px; font-size: small"))  %>&nbsp; &nbsp;</td><td><i><%= escape_javascript("posted on : " + @post.created_at.to_s.chomp('UTC'))%></i>&nbsp; &nbsp;</td></tr>");
$("form[data-remote]").remove();
$("a[href='<%= new_post_comment_path(@post.id) %>']").fadeIn();

app/views/comments/destroy.js.erb
$("body table tbody").remove();	//supprime LE COMMENT
$("form#new_post_comment").remove();	//supprimer le formulaire new comment
$("a[href='<%= new_post_comment_path %>']").fadeIn();	//faire apparaitre le lien vers new

app/views/comments/new.html.erb
<h1> New Comment <h1>
<div class='formcomment'>
<%= render 'commentform' %>
</div>
<br />

app/views/comments/new.js.erb
$("a[href='<%= new_post_comment_path(@post) %>']").after("<%= escape_javascript(render 'comments/commentform') %>"); //récup lien page html et ajout (after) d'un formulaire form
$("form[data-remote].commentform").attr("data-remote", true);	//récup du form en rajoutant attribut data-remote ajax (si true, soumettre avec AJAX)
$("a[href='<%= new_post_comment_path(@post) %>']").fadeOut()	//cacher le lien puisque le formulaire création y est déjà

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog d'Hélène</title>
  <%= stylesheet_link_tag    "application" %>
  <%= stylesheet_link_tag    "main" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="border">
<div class="content-navigation">
<% if current_user then %> 
<p align=right> Connected as <i><%= User.find(current_user.id).email %></i> | <%= link_to 'Log out', "/sessions/current_user", :method => 'delete'%> | <%= link_to 'Delete your account', "/users/#{session[:user_id]}", :method => 'delete'%> </p>
<% end %>
<div class=accueil> Welcome on Helen's blog !</div>
<%= yield %>
</div>
</div>
</body>
</html>

app/views/marks/_markform.html.erb
<%= form_tag("/posts/#{@post.id}/marks") %>
<% @tableau = {"0" => 0, "1" => 1, "2" => 2, "3" => 3, "4" => 4, "5" => 5} %>
  <br />
  <div class="field">
    <%= label_tag :value %>
    <%= select_tag "value", options_for_select(@tableau) %>
  </div>
  <div class="actions">
    <%= submit_tag value = "Submit Mark" %>
  </div>

app/views/marks/create.js.erb
$("span").each(function (i) {if (this.id="mark") {$(this).hide();}});
$("#mark").after('<span id="mark"><p><b> Actual mark of this post :  &nbsp;</b>  <span id="notepost"><%= escape_javascript(sprintf("%.2f",@post.note)) + "/5"  %></span>&nbsp<i>|with <span id="nbmark"> <%= @post.marks.length %> marks </span></i> </p></span>');
$("form[data-remote]").remove();
$("a[href='<%= new_post_mark_path(@post.id) %>']").fadeIn();

app/views/marks/new.html.erb
<h1> New Mark <h1>
<%= render 'markform' %>
<br />

app/views/marks/new.js.erb
$("a[href='<%= new_post_mark_path(@post) %>']").after("<%= escape_javascript(render 'marks/markform') %>");
$("form[data-remote]").attr("data-remote", true);	
$("a[href='<%= new_post_mark_path(@post) %>']").fadeOut();

app/views/posts/_commentform.html.erb
<%= form_tag("/posts/#{@post.id}/comments", :remote=>true) %>

  <div class="field">
    <%= label_tag :author %><br />
    <%= text_field_tag :author %>
  </div>
  <br />
  <div class="field">
    <%= label_tag :body %><br />
    <%= text_area_tag :body %>
  </div>
  <div class="actions">
    <%= submit_tag value = "Create Comment" %>
  </div>

app/views/posts/_commentlist.html.erb
<% @post.comments.each do |comment| %>
<tr>
	<td> <%= comment.author %> &nbsp;&nbsp;</td>
	<td><%= comment.body%> &nbsp;&nbsp;</td>
	<td><%= button_to('Delete Comment', "/posts/#{@post.id}/comments/#{comment.id}", :confirm => 'Are you sure?', :method => "delete", :style => "background: #F1F1F1; color: #2CA2AF; width:130px; height: 19px; font-size: small") %>&nbsp; &nbsp;</td>
	<td><i><%= "posted on : " + @post.created_at.to_s.chomp('UTC') %></i></td>
</tr>
<% end %>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>

<% @post.user_id = session[:user_id] %>
<% @post.note = 0.0 %>

  <div class="field">
    <%= f.hidden_field :user_id %><br />
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <br />
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.hidden_field :note %><br />
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  <br />
<% end %>

app/views/posts/_markform.html.erb
<%= form_tag("/posts/#{@post.id}/marks",:remote=>true, :name => "formnote") %>
<% @tableau = {"0" => 0, "1" => 1, "2" => 2, "3" => 3, "4" => 4, "5" => 5} %>
  <br />
  <div class="field">
    <%= label_tag :value %>
    <%= select_tag "value", options_for_select(@tableau) %>
  </div>
  <div class="actions">
    <%= submit_tag value = "Submit Mark" %>
  </div>

app/views/posts/create.js.erb
$("body table tbody").append("<tr><td><%= escape_javascript(@post.title)%></td><td><%= escape_javascript(@post.body)%></td><td><%= escape_javascript(button_to('Show Post', post_path(@post.id), :method => "get", :style => "background: #F1F1F1; color: #2CA2AF")) %>&nbsp; &nbsp;</td><td><%= escape_javascript(button_to('Edit Post', edit_post_path(@post.id), :method => "get", :style => "background: #F1F1F1; color: #2CA2AF")) %>&nbsp; &nbsp;</td><td><%= escape_javascript(button_to('Delete Post', @post, :method => "delete", :style => "background: #F1F1F1; color: #2CA2AF")) %>&nbsp; &nbsp;</td><td><i><%= "| (yours)" %> &nbsp; &nbsp;</i></td></tr>");
$("form#new_post").remove();
$("a[href='<%= new_post_path %>']").fadeIn();

//append : ajout du contenu -> nom de la tache, lien vers show, edit et destroy
//surppression formulaire nouvelle tache
//ajout lien nouvelle tache

app/views/posts/destroy.js.erb
$("body table tbody").remove();	//supprime le post
$("form#new_post").remove();	//supprimer le formulaire new POST
$("a[href='<%= new_post_path %>']").fadeIn();	//faire apparaitre le lien vers new

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', post_path(@post) %> | 
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>


<table>
  <tr>
    <th>Title &nbsp;</th>
    <th>Body &nbsp;</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @posts.each do |post| %>

    <tr>
	<td> <%= post.title %> &nbsp; &nbsp;</td>
	<td><%= post.body %> &nbsp; &nbsp;</td>
	<td><%= button_to('Show Post', post_path(post.id), :method => "get", :style => "background: #F1F1F1; color: #2CA2AF") %>&nbsp; &nbsp;</td>
	<% if current_user and current_user.id == post.user_id then %>
		<td><%= button_to('Edit Post', edit_post_path(post.id), :method => "get", :style => "background: #F1F1F1; color:#2CA2AF") %>&nbsp; &nbsp;</td>
		<td><%= button_to('Delete Post', post, :confirm => 'Are you sure?', :method => "delete", :style => "background: #F1F1F1; color: #2CA2AF") %>&nbsp; &nbsp;</td>
	<% else %>
		<td> </td>
		<td> </td> 
	<%end%>
	<% if  (current_user == nil or current_user.id != post.user_id) then %>
		<td><i><%= "| posted by " + User.find(post.user_id).email %> &nbsp; &nbsp;</i></td>
	<% else %>
		<td><i><%= "| (yours)" %> &nbsp; &nbsp;</i></td>
	<%end%>
    </tr>
  <% end %>
</table>

<br />
<% if current_user then %>
<%= link_to 'New Post', new_post_path, :remote => true %> | <%= link_to 'Log out', "/sessions/current_user", :method => 'delete'%>  | <%= link_to 'Delete your account', "/users/#{session[:user_id]}", :method => 'delete'%>
<% else %>
<%= link_to 'Log in', new_session_path %> | <%= link_to 'Create an account', new_user_path %>
<% end %>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/new.js.erb
$("a[href='<%= new_post_path %>']").after("<%= escape_javascript(render 'form') %>"); //récup lien page html et ajout (after) d'un formulaire form
$("form#new_post").attr("data-remote", true);	//récup du form en rajoutant attribut data-remote ajax (si true, soumettre avec AJAX)
$("a[href='<%= new_post_path %>']").fadeOut()	//cacher le lien puisque le formulaire création y est déjà

app/views/posts/show.html.erb
<h1>Post details</h1>

<div class="affichagepost">
<p>
  <b>Title: &nbsp;</b>
  <%= @post.title %>
</p>

<p>
  <b>Body: &nbsp;</b>
  <%= @post.body %>
</p>

<p>
  <b>Posted by : &nbsp;</b>
  <%= User.find(@post.user_id).email %>
</p>

<p>
  <b> Creation : &nbsp;</b>
  <%= @post.created_at.to_s.chomp('UTC') %>
</p>

<p>
  <b> Last update : &nbsp;</b>
  <%= @post.updated_at.to_s.chomp('UTC') %>
</p>

<span id="mark">
<p>
  <b> Actual mark of this post :  &nbsp;</b>  <span id="notepost"><%= sprintf("%.2f",@post.note) + "/5"  %></span>&nbsp <i>|with <span id="nbmark"> <%= @post.marks.length %> marks </span></i>
</p>
</span>


<p> 
 <%= link_to 'Mark this post', new_post_mark_path(@post.id), :remote => true %>
</p>
<br />

</div>

<HR width=70% align=left>

<p>
<h3>Comments on the post</h3>
<div class="affichagecomment">
<table>
  <tr>
    <th>Author &nbsp;</th>
    <th>Body &nbsp;</th>
		<th></th>
    <th></th>
    <th></th>
  </tr>
	<%= render 'comments/commentlist', :remote => true %>
</table>
<br />
</p>
</div>
<HR width=70% align=left>

<p>
<h3>New comment</h3>
<%= link_to 'Add a comment', new_post_comment_path(@post), :remote => true %>
</p>

<HR width=70% align=left>

<p>
<% if current_user and current_user.id == @post.user_id then %>
<%= link_to 'Edit', edit_post_path(@post) %> |
<%end%>
<% if !current_user then %>
<%= link_to 'Log in', new_session_path %> |
<% end %>

<%= link_to 'Back', posts_path %>  
</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>
<br />
<div class="flash">
<% if flash[:error] then %>
	<%=  "* " + flash[:error] %>
<%end%>
</div>